# Generated by Django 4.2.2 on 2023-07-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='hiring_data',
            field=models.DateTimeField(null=True),
        ),
    ]
