# Generated by Django 4.2.2 on 2023-07-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_students_father_students_mother_students_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='father',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
