# Generated by Django 4.2.2 on 2023-07-03 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_alter_students_father_alter_students_mother_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='father',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='mother',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
