# Generated by Django 4.2.2 on 2023-07-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_alter_students_father_alter_students_mother_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='id_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
