# Generated by Django 4.2.2 on 2023-07-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_students_id_number_students_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
    ]
