# Generated by Django 4.2.2 on 2023-07-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0016_alter_staffs_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='subject_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects'),
        ),
    ]
