# Generated by Django 4.2.2 on 2023-07-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0017_staffs_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects'),
        ),
    ]
