# Generated by Django 4.2.2 on 2023-07-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0019_remove_staffs_course_id_remove_staffs_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects'),
        ),
    ]
