# Generated by Django 4.2.2 on 2023-07-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0020_staffs_course_id_staffs_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='subject_id',
        ),
    ]
