# Generated by Django 4.2.2 on 2023-07-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0021_remove_staffs_subject_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChefToStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationChefToStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
