# Generated by Django 4.2.2 on 2023-07-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0023_notificationstafftostudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStaffToCheff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chef_id', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStudentToCheff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chef_id', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
