# Generated by Django 4.2.2 on 2023-07-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0024_notificationstafftocheff_notificationstudenttocheff'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChefToStaffLeave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStaffToCheffLeave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chef_id', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
