# Generated by Django 4.2.2 on 2023-07-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0025_notificationcheftostaffleave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
